# Generated by Django 3.1.4 on 2021-01-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='votes.team'),
        ),
    ]
