# Generated by Django 3.1.4 on 2021-03-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1),
        ),
    ]
